package com.shinoow.acblocks.common.structures;

import java.util.Random;

import com.shinoow.abyssalcraft.AbyssalCraft;
import com.shinoow.abyssalcraft.api.block.ACBlocks;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.util.BlockPos;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;

public class ACPlatform2 extends WorldGenerator {

	@Override
	public boolean generate(World world, Random random, BlockPos pos) {

		int i = pos.getX();
		int j = pos.getY();
		int k = pos.getZ();

		world.setBlockState(new BlockPos(i + 0, j + 0, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 1), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 2), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 3), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 4), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 5), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 0, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 1), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 2), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 3), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 4), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 5), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 1, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 1), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 2), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 3), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 4), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 5), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 0, j + 2, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 1), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 2), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 3), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 4), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 5), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 0, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 2), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 3), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 4), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 1), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 2), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 3), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 4), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 5), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 2, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 0), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 1), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 2), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 3), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 4), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 5), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 0, k + 6), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 1), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 2), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 3), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 4), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 5), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 1, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 1), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 2), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 3), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 4), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 5), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 2, j + 2, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 0), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 1), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 2), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 3), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 4), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 5), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 0, k + 6), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 1), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 2), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 3), Blocks.glowstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 4), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 5), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 1, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 1), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 2), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 3), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 4), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 5), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 3, j + 2, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 0), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 1), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 2), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 3), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 4), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 5), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 0, k + 6), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 1), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 2), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 3), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 4), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 5), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 1, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 1), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 2), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 3), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 4), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 5), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 4, j + 2, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 1), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 2), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 3), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 4), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 5), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 0, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 2), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 3), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 4), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 1), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 2), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 3), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 4), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 5), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 5, j + 2, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 1), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 2), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 3), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 4), ACBlocks.darkstone.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 5), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 0, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 1), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 2), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 3), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 4), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 5), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 1, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 0), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 1), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 2), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 3), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 4), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 5), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 6, j + 2, k + 6), Blocks.air.getDefaultState(), 2);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 1), Blocks.redstone_torch.getStateFromMeta(5), 2);
		world.setBlockState(new BlockPos(i + 1, j + 1, k + 5), Blocks.redstone_torch.getStateFromMeta(5), 2);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 1), Blocks.redstone_torch.getStateFromMeta(5), 2);
		world.setBlockState(new BlockPos(i + 5, j + 1, k + 5), Blocks.redstone_torch.getStateFromMeta(5), 2);

		return true;
	}
}