package com.shinoow.acblocks.common.structures;

import java.util.Random;

import com.shinoow.abyssalcraft.AbyssalCraft;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;

public class ACPlatform2 extends WorldGenerator {

	@Override
	public boolean generate(World world, Random random, int i, int j, int k) {

		world.setBlock(i + 0, j + 0, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 0, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 0, k + 2, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 0, j + 0, k + 3, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 0, j + 0, k + 4, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 0, j + 0, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 0, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 0, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 0, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 0, k + 1, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 1, j + 0, k + 2, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 1, j + 0, k + 3, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 1, j + 0, k + 4, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 1, j + 0, k + 5, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 1, j + 0, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 2, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 1, j + 1, k + 3, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 1, j + 1, k + 4, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 1, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 0, k + 0, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 2, j + 0, k + 1, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 2, j + 0, k + 2, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 2, j + 0, k + 3, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 2, j + 0, k + 4, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 2, j + 0, k + 5, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 2, j + 0, k + 6, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 2, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 1, k + 1, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 2, j + 1, k + 2, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 2, j + 1, k + 3, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 2, j + 1, k + 4, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 2, j + 1, k + 5, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 2, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 2, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 2, j + 2, k + 3, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 2, j + 2, k + 4, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 2, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 2, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 0, k + 0, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 3, j + 0, k + 1, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 3, j + 0, k + 2, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 3, j + 0, k + 3, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 3, j + 0, k + 4, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 3, j + 0, k + 5, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 3, j + 0, k + 6, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 3, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 1, k + 1, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 3, j + 1, k + 2, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 3, j + 1, k + 3, Blocks.glowstone, 0, 2);
		world.setBlock(i + 3, j + 1, k + 4, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 3, j + 1, k + 5, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 3, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 2, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 3, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 4, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 3, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 3, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 0, k + 0, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 4, j + 0, k + 1, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 4, j + 0, k + 2, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 4, j + 0, k + 3, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 4, j + 0, k + 4, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 4, j + 0, k + 5, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 4, j + 0, k + 6, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 4, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 1, k + 1, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 4, j + 1, k + 2, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 4, j + 1, k + 3, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 4, j + 1, k + 4, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 4, j + 1, k + 5, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 4, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 2, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 4, j + 2, k + 3, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 4, j + 2, k + 4, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 4, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 4, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 0, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 0, k + 1, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 5, j + 0, k + 2, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 5, j + 0, k + 3, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 5, j + 0, k + 4, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 5, j + 0, k + 5, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 5, j + 0, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 1, k + 2, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 5, j + 1, k + 3, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 5, j + 1, k + 4, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 5, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 5, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 0, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 0, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 0, k + 2, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 6, j + 0, k + 3, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 6, j + 0, k + 4, AbyssalCraft.Darkstone, 0, 2);
		world.setBlock(i + 6, j + 0, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 0, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 1, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 0, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 1, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 2, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 3, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 4, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 5, Blocks.air, 0, 2);
		world.setBlock(i + 6, j + 2, k + 6, Blocks.air, 0, 2);
		world.setBlock(i + 1, j + 1, k + 1, Blocks.redstone_torch, 5, 2);
		world.setBlock(i + 1, j + 1, k + 5, Blocks.redstone_torch, 5, 2);
		world.setBlock(i + 5, j + 1, k + 1, Blocks.redstone_torch, 5, 2);
		world.setBlock(i + 5, j + 1, k + 5, Blocks.redstone_torch, 5, 2);

		return true;
	}
}